name: flutter_gemini
description: Flutter Google Gemini SDK. Google Gemini is a set of cutting-edge large language models 
  (LLMs) designed to be the driving force behind Google's future AI initiatives.
version: 3.0.0-dev.1
repository: https://github.com/babakcode/flutter_gemini
topics:
  - gemini
  - ai
  - google-gemini
  - flutter-gemini
screenshots:
  - description: Flutter_Gemini example screenshot
    path: ./screenshots/gemini_screenshot.png
  - description: Flutter_Gemini example
    path: ./screenshots/gemini_cover.jpeg

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  mime: ^2.0.0

dev_dependencies:
  test: ^1.24.0
  flutter_lints: ^2.0.0
  json_convert: ^1.1.0
  build_runner: ^2.4.7